# x = set()
# print(type(x))
# print(x)
# x.add('data1')
# x.add('data2')
# x.add('data3')
# x.add('data1')
# x.add('data4')
# x.add('data5')
# x.add('data3')
# x.add('data6')
# x.add('data7')
# x.add('data5')
# x.add('data8')
# print(x)

# list1 = [9, 1, 8, 2, 7, 3, 6, 4, 5, 5, 4, 6, 3, 7, 2, 8, 1]
# print(f'List1: {list1}')
# unique_list = set(list1)
# print(f'Unique List: {unique_list}')
# print(f'Popped Item: {unique_list.pop()}')
# print(f'Unique List: {unique_list}')
# removed_5 = unique_list.remove(5)
# print(f'Removed Item: {removed_5}')
# print(f'Unique List: {unique_list}')
# discard_3 = unique_list.discard(3)
# print(f'Discarded Item: {discard_3}')
# print(f'Unique List: {unique_list}')
# discard_10 = unique_list.discard(10)
# print(f'Discarded Item: {discard_10}')
# print(f'Unique List: {unique_list}')
# removed_10 = unique_list.remove(10)
# # print(f'Removed Item: {removed_10}') # -> error
# print(f'Unique List: {unique_list}')
# copied_set = unique_list.copy()
# print(f'Copied Set: {copied_set}')
# copied_set.clear()
# print(f'Cleared Copied Set: {copied_set}')

# set1 = set([1, 2, 3, 4, 5])
# set2 = set([1, 3, 5, 7, 9])
# set3 = set()
# set3.add(frozenset(set1))
# set3.add(frozenset(set2))
# print(set3)

# a = set(['A', 'B', 'C', 'D'])
# print(a) -> Error

# set1 = set()
# set1.add('A')
# set1.add('B')
# set1.add('C')
# set1.add('D')
# set1.add('E')
# set1.add('F')
# set1.add('G')
# print(f'Set1: {type(set1)}')
# set2 = set()
# set2.add('A')
# set2.add('C')
# set2.add('E')
# set2.add('G')
# print(f'Set2: {type(set2)}')
# set3 = set1.difference(set2)
# print(f'Set3: {type(set3)}')
# print(set3)

# set1 = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'}
# print(f'Set1: {type(set1)}')
# set2 = {'A', 'C', 'E', 'G'}
# print(f'Set2: {type(set2)}')
# set3 = set1 - set2
# print(f'Set3: {type(set3)}')
# print(set3)